services:
- name: mongo
  image: mongo
  env:
    - name: ME_CONFIG_MONGODB_ADMINUSERNAME
      value: root
    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
      value: example
  bindings:
    - port: 27017
- name: mongo-express
  image: mongo-express
  bindings:
    - port: 8081
      containerPort: 8081
      protocol: http
  env:
    - name: ME_CONFIG_MONGODB_ADMINUSERNAME
      value: root
    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
      value: example