kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: multi-project
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/part-of: multi-project
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
...
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: multi-project
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
  type: ClusterIP
  ports:
  - name: rabbitmq
    protocol: TCP
    port: 5672
    targetPort: 5672
...
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: binding-production-rabbit-rabbit-secret
# type: Opaque
# stringData:
#   connectionstring: amqp://rabbitmq:5672