version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
  postgres: # TODO needed to switch name here for some reason
    image: postgres:9.4
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
  vote:
    build:
      context: ./vote
    ports:
      - 5000:80
  result:
    build:
      context: ./results
    ports:
      - 5001:80
  worker:
    build:
      context: ./worker