kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: multi-project
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/part-of: multi-project
    spec:
      containers:
      - name: backend
        image: rynowak/backend:0.1.18-alpha.gbab4910d38
        env:
        - name: ASPNETCORE_URLS
          value: http://*:7000
        - name: SERVICE__FRONTEND__PORT
          value: '8000'
        - name: SERVICE__FRONTEND__HOST
          value: 'frontend'
        volumeMounts:
        - name: rabbit-rabbit
          mountPath: /var/tye/bindings/rabbit-rabbit
          readOnly: true
        ports:
        - containerPort: 7000
      volumes:
      - name: rabbit-rabbit
        secret:
          secretName: binding-production-rabbit-rabbit-secret
          items:
          - key: connectionstring
            path: CONNECTIONSTRING__RABBIT
...
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: multi-project
spec:
  selector:
    app.kubernetes.io/name: backend
  type: ClusterIP
  ports:
  - name: backend
    protocol: TCP
    port: 7000
    targetPort: 7000
...
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: multi-project
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: multi-project
    spec:
      containers:
      - name: frontend
        image: rynowak/frontend:0.1.18-alpha.gbab4910d38
        env:
        - name: ASPNETCORE_URLS
          value: http://*:8000
        - name: SERVICE__BACKEND__PORT
          value: '7000'
        - name: SERVICE__BACKEND__HOST
          value: 'backend'
        volumeMounts:
        - name: rabbit-rabbit
          mountPath: /var/tye/bindings/rabbit-rabbit
          readOnly: true
        ports:
        - containerPort: 8000
      volumes:
      - name: rabbit-rabbit
        secret:
          secretName: binding-production-rabbit-rabbit-secret
          items:
          - key: connectionstring
            path: CONNECTIONSTRING__RABBIT
...
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: multi-project
spec:
  selector:
    app.kubernetes.io/name: frontend
  type: ClusterIP
  ports:
  - name: frontend
    protocol: TCP
    port: 8000
    targetPort: 8000
...
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: worker
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: multi-project
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: worker
        app.kubernetes.io/part-of: multi-project
    spec:
      containers:
      - name: worker
        image: rynowak/worker:0.1.18-alpha.gbab4910d38
        env:
        - name: SERVICE__BACKEND__PORT
          value: '7000'
        - name: SERVICE__BACKEND__HOST
          value: 'backend'
        - name: SERVICE__FRONTEND__PORT
          value: '8000'
        - name: SERVICE__FRONTEND__HOST
          value: 'frontend'
        volumeMounts:
        - name: rabbit-rabbit
          mountPath: /var/tye/bindings/rabbit-rabbit
          readOnly: true
      volumes:
      - name: rabbit-rabbit
        secret:
          secretName: binding-production-rabbit-rabbit-secret
          items:
          - key: connectionstring
            path: CONNECTIONSTRING__RABBIT
...
