name: CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 3.1.100
     
    - name: dotnet build
      run: dotnet build tye.sln -c Release
      
    - name: dotnet test
      run: dotnet test tye.sln -c Release --no-build

    - name: dotnet pack
      run: |
        mkdir ./artifacts
        dotnet pack tye.sln -c Release --no-build -o ./artifacts

